version: '3.7'

services:
  clickhouse-server:
    image: yandex/clickhouse-server:20.4
    container_name: clickhouse_test
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"

  mongo:
    container_name: mongo_test
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  postgres:
    image: postgres:15.3
    container_name: postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"