version: '3.9'

services:
  reviews_api:
    container_name: reviews_api
    restart: unless-stopped
    build:
      context: ./ReviewsAPI
      dockerfile: Dockerfile
    networks:
      - application_network
    env_file:
      - .env
    volumes:
      - ./ReviewsAPI:/opt/app
      - logs:/opt/logs
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    depends_on:
      mongos:
        condition: service_healthy
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

#______________Auth_______________
  auth_api:
    container_name: AuthAPI
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 9999 --reload
    env_file:
      - .env
    volumes:
      - ./AuthAPI:/opt/app
    build:
      context: AuthAPI
      dockerfile: dockerfile
    depends_on:
      auth_postgres:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - application_network
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Nginx/auth_api.conf:/etc/nginx/conf.d/auth_api.conf:ro
      - ./Nginx/reviews_api.conf:/etc/nginx/conf.d/reviews_api.conf:ro
    depends_on:
      auth_api:
        condition: service_started
      reviews_api:
        condition: service_started
    ports:
      - "8001:8001"
      - "3000:3000"
    networks:
      - application_network
  
  auth_jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: auth_jaeger
    ports:
      - '6831:6831/udp'
      - '16686:16686'
    depends_on:
      - auth_api
      - nginx
    networks:
      - application_network

    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5

volumes:
  logs:

networks:
  application_network:
