FROM python:3.10
WORKDIR /tests
COPY /functional/requirements.txt .
RUN apt-get update

RUN pip install --upgrade pip --no-cache-dir \
     && pip install -r requirements.txt --no-cache-dir

COPY ./entrypoint.sh /
RUN chmod 777 /entrypoint.sh
RUN apt-get install -y netcat-traditional
COPY . /tests/

ENTRYPOINT ["/entrypoint.sh"]