# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wemake-python-styleguide flake8-html flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --max-line-length 300 --exit-zero --format=html --htmldir=reports/ugc_service/styleguide/
        
  notify:
    runs-on: ubuntu-latest
    if: cancelled() == false
    needs: build
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.tg_to }}
          token: ${{ secrets.tg_token }}
          format: html
          message: |
            <b>${{ github.workflow }}</b>
            <b>Репозиторий:</b> <a href="https://github.com/${{github.repository}}">${{github.repository}}</a>
            <b>Статус:</b> ${{ needs.build.result }}
            <b>Детали:</b> <a href="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}">Просмотреть</a>
